[package]
name = "bootloader-uefi"
version = "0.0.0"

[dependencies]
uefi = {path = "../libuefi"}
utf16_literal = { path = "../libuefi/utf16_literal" }

[lib]
crate-type = ["staticlib"]
name = "bootloader_uefi"
path = "main.rs"
